config/routes.rb
OMRails::Application.routes.draw do
  mount Commontator::Engine => '/commontator'
  resources :pins do
  member do
    put "like", to: "pins#upvote"
    put "dislike", to: "pins#downvote"
  end
end
  devise_for :users
    get "users/show"
    root  :to =>"pins#index"
    get 'about' => 'pages#about'
    get 'users/:id' => 'users#show', as: :user

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>", :tiny => "50x50" }

validates :image, presence: true
acts_as_commontable
acts_as_votable

 


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  require 'will_paginate/array'
  def index
   @pins = Pin.all.sort_by{|pin|-pin.likes.size}.paginate(:page => params[:page], :per_page => 20)
    

 end

  def show
    commontator_thread_show(@pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end
    def upvote
  @pin = Pin.find(params[:id])
    @pin.liked_by current_user
    if @pin.vote_registered?
   redirect_to :back, notice: "Thanks for voting!"
  else
   redirect_to :back, notice: "You may only vote once, either for or against." 
 end
end

def downvote
  @pin = Pin.find(params[:id])
  @pin.disliked_by current_user
   if @pin.vote_registered?
   redirect_to :back, notice: "Thanks for voting!"
  else
   redirect_to :back, notice: "You may only vote once, either for or against." 
 end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<div class=" panel-body">
<%= form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, " Description (Optional)" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "SUBMIT POST", class: "btn btn-info btn-block btn-lg" %>
  </div>
<% end %>
</div>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>EDIT POST</h1>
  </div> <!-- panel-heading -->
    <%= render 'form' %>
  <div class="panel-footer">
    <div class="edit-links">
    <%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %>
    </div> <!-- edit-links -->
  </div> <!-- panel-footer -->
</div> <!-- panel-default -->

app/views/pins/index.html.erb
<% if user_signed_in? %>
<div class="post-contents">

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-success">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p class="description-index" id="pins">
          <% if pin.description.length >= 50 %>
          <%= pin.description[0,50] + "..." %>
          <% else %>
          <%= pin.description %>
          <% end %>
          
        </p>
        <p class="username">
          <div class="tiny-image">
          <%= link_to image_tag(pin.user.image.url (:tiny)), pin.user %>
          <strong>
            <%= link_to pin.user.name, pin.user if pin.user %>
          </strong>
          </div>
        </p>
          <%= link_to raw('<span class="glyphicon glyphicon-hand-up"></span>'), like_pin_path(pin), method: :put %> <span class="vote"><%= pin.likes.size%></span>
          
          <%= link_to  raw('<span class="glyphicon glyphicon-hand-down"></span>'), dislike_pin_path(pin), method: :put %><span class="vote"><%= pin.dislikes.size%></span>
       
        <% if pin.user == current_user %>
          <div class="actions">
          <%= link_to raw('<span class="glyphicon glyphicon-edit"></span>Edit'), edit_pin_path(pin) %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>Destroy'), pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center custom-pagination">
   <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>
</div>
<% else %>
<%= render 'pages/home'%>
<% end %>

app/views/pins/new.html.erb
<div class="panel-default panel">
<div class="panel-heading">
	<h1>NEW POST</h1>
</div>
<%= render 'form' %>
<div class="panel-footer text-center">
<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-info">
		<div class="panel-heading center show-pin">
			<%= image_tag @pin.image.url(:medium) %>
		</div>
		<div class="panel-body">
		<p><%= @pin.description %></p>
		
		 
      <p><strong class="show-image"><%= link_to image_tag(@pin.user.image.url(:tiny)), user_path(@pin.user)if @pin.user %></strong>
			<strong><%= link_to @pin.user.name, user_path(@pin.user)if @pin.user %></strong></p>
      <p><%= @pin.user.name %></p>
		<div class="comment-box"><%= commontator_thread(@pin)%></div>
		<div class="edit-links">
		<% if @pin.user == current_user %>
			<%= link_to raw('<span class="glyphicon glyphicon-edit edit-links"></span> Edit'), edit_pin_path(@pin) %> |
			<%= link_to raw('<span class="glyphicon glyphicon-trash edit-links"></span> Delete'), edit_pin_path(@pin) %>
		<% end %>
     </div>
      <%= link_to "Back", pins_path, class: "btn btn-info" %>
		</div>
	</div>
</div>