config/routes.rb
OMRails::Application.routes.draw do
  mount Commontator::Engine => '/commontator'
  resources :pins do
  member do
    put "like", to: "pins#upvote"
    put "dislike", to: "pins#downvote"
  end
end
  devise_for :users
    get "users/show"
    root  :to =>"pins#index"
    get 'about' => 'pages#about'
    get 'users/:id' => 'users#show', as: :user

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default " role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/" class="navbar-brand">
      <span class="omg">R</span>UGGED
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
   
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to raw('<span class="glyphicon glyphicon-heart"></span>  Home'), root_path%>
      </li>
       <% if user_signed_in? %>
       <li>
        <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>  New Post'), new_pin_path %>
      </li>
        <li>
          <%= link_to raw('<span class="glyphicon glyphicon-wrench"></span> Edit Account'), edit_user_registration_path %>
        </li>

    <li>
          <%= link_to raw('<span class="glyphicon glyphicon-user"></span> My Profile'), current_user %>
        </li>

       <li>
        <%= link_to raw('<span class="glyphicon glyphicon-log-out"></span> Log out'), destroy_user_session_path, method: :delete %>
      </li>
       <%else %>
       <li>
        <%= link_to raw('<span class="glyphicon glyphicon-log-in"></span>  Sign in'), new_user_session_path %>
     </li>
    <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		  <title>RUGGED</title>
		  <meta name="description" content="Rugged is the premier site for all things outdoors. Post pictures of your favorite outdoor adventures, find new adventurer's or just be amazed by other's outdoor experiences!"> <meta http-equiv="content-type" content="text/html;charset=UTF-8">
		  <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
		  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		  <%= csrf_meta_tags %>
		  <%= favicon_link_tag 'favicon.ico' %>
		  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>

<% if user_signed_in? %>
	<%= render 'layouts/header'%>
<% else %>
<% end %>

		<div class="">

			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info")%>
			<% end %>
			<%= yield %>
		</div>

		

	</body>
</html>